In [1]:
import numpy as np

In [2]:
x = np.array([-1, 0, 1])

In [3]:
y = np.array([-2, 0, 2])

In [4]:
X, Y = np.meshgrid(x, y)

In [5]:
X

array([[-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1]])

In [6]:
Y

array([[-2, -2, -2],
       [ 0,  0,  0],
       [ 2,  2,  2]])

In [7]:
X = (X + Y) ** 2

In [8]:
X

array([[9, 4, 1],
       [1, 0, 1],
       [1, 4, 9]], dtype=int32)

In [9]:
np.identity (5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
np.eye (4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [11]:
np.eye (4, k=-2)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [12]:
np.eye (4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.]])

In [13]:
np.eye (4, k=-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [14]:
np.eye (4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.diag(np.arange(0, 20, 5))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [16]:
np.diag(np.arange(0, 100, 10))

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 10,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 20,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 30,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 40,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 50,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 60,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 70,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 80,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 90]])

In [17]:
a = np.arange(0, 11)

In [18]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
a[0]

0

In [20]:
a[10]

10

In [21]:
a[-1]

10

In [22]:
a[1:-1]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
a[1:-1:2]

array([1, 3, 5, 7, 9])

In [24]:
a[1:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
a[:1]

array([0])

In [26]:
a[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
a[-1:]

array([10])

In [28]:
a[-5:]

array([ 6,  7,  8,  9, 10])

In [29]:
a[:-5]

array([0, 1, 2, 3, 4, 5])

In [30]:
a[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
a[::]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
a{::-1}

SyntaxError: invalid syntax (<ipython-input-32-ea7db7174688>, line 1)

In [33]:
a[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [34]:
a[::-3]

array([10,  7,  4,  1])

In [35]:
f = lambda m, n: n + 10 * m 

In [36]:
A = np.fromfunction (f, (6, 6), dtype=int)

In [37]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [38]:
A [:, 1]

array([ 1, 11, 21, 31, 41, 51])

In [39]:
A [:, 2]

array([ 2, 12, 22, 32, 42, 52])

In [40]:
A [:, 0]

array([ 0, 10, 20, 30, 40, 50])

In [41]:
A [0, :]

array([0, 1, 2, 3, 4, 5])

In [42]:
A [4, :]

array([40, 41, 42, 43, 44, 45])

In [43]:
A [:3, :3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [44]:
A [3:, 3:]

array([[33, 34, 35],
       [43, 44, 45],
       [53, 54, 55]])

In [45]:
A [3:, 2:]

array([[32, 33, 34, 35],
       [42, 43, 44, 45],
       [52, 53, 54, 55]])

In [46]:
B = A [1:5, 1:5]

In [47]:
B

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [49]:
B[:, :] = 0

In [50]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [10,  0,  0,  0,  0, 15],
       [20,  0,  0,  0,  0, 25],
       [30,  0,  0,  0,  0, 35],
       [40,  0,  0,  0,  0, 45],
       [50, 51, 52, 53, 54, 55]])

In [51]:
C = B [1:3, 1:3].copy()

In [52]:
C

array([[0, 0],
       [0, 0]])

In [53]:
C[:, :]=1

In [54]:
C

array([[1, 1],
       [1, 1]])

In [55]:
B

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [56]:
A = np.linspace(0, 1, 11)

In [57]:
A

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [58]:
A [np.array([0, 2, 4])]

array([0. , 0.2, 0.4])

In [59]:
A [[0, 2, 4]]

array([0. , 0.2, 0.4])

In [60]:
A > 0.5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [61]:
A [A > 0.5]

array([0.6, 0.7, 0.8, 0.9, 1. ])

In [62]:
data = np.array ([[1,2], [3,4]])

In [63]:
np.reshape(data, (1,4))

array([[1, 2, 3, 4]])

In [64]:
data.reshape(4)

array([1, 2, 3, 4])

In [65]:
data = np.array([[1, 2], [3, 4]])

In [66]:
data

array([[1, 2],
       [3, 4]])

In [68]:
data.flatten().shape

(4,)

In [69]:
data = np.arange(0, 5)

In [70]:
column = data[:, np.newaxis]

In [71]:
column

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [72]:
row = data[np.newaxis, :]

In [73]:
row

array([[0, 1, 2, 3, 4]])

In [74]:
data = np.arange(5)

In [75]:
data

array([0, 1, 2, 3, 4])

In [76]:
np.vstack((data, data, data))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [77]:
data = np.arange(5)

In [78]:
data

array([0, 1, 2, 3, 4])

In [79]:
np.hstack((data, data, data))

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [83]:
data = np.arange(0,5)

In [84]:
data

array([0, 1, 2, 3, 4])

In [85]:
np.hstack((data, data, data))

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [87]:
data = data[:, np.newaxis]

In [88]:
np.hstack((data, data, data))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [89]:
x = np.array([[1, 2], [3, 4]])

In [90]:
y = np.array([[5, 6], [7, 8]])

In [91]:
x + y

array([[ 6,  8],
       [10, 12]])

In [92]:
y - x

array([[4, 4],
       [4, 4]])

In [93]:
x * y

array([[ 5, 12],
       [21, 32]])

In [94]:
y / x

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [95]:
x * 2

array([[2, 4],
       [6, 8]])

In [96]:
2 ** x

array([[ 2,  4],
       [ 8, 16]], dtype=int32)

In [97]:
y / 2

array([[2.5, 3. ],
       [3.5, 4. ]])

In [98]:
(y / 2).dtype

dtype('float64')

In [99]:
x = np.array([1, 2, 3, 4]).reshape(2,2)

In [100]:
z = np.array([1, 2, 3, 4])

In [101]:
x / z

ValueError: operands could not be broadcast together with shapes (2,2) (4,) 